name: Compile LLVM

on: [push]

jobs:
  compile-llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Download LLVM sources
        uses: teddyking/dependency-action@master
        with:
          deps: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/llvm-project-11.0.1.src.tar.xz
      - name: Configure CMake
        run: |
          sudo mkdir /llvm-build
          cd /llvm-build
          ls /github/home
          sudo cmake -G Ninja /github/home/llvm-project-11.0.1.src
      - name: Compile LLVM
        run: |
          cd /llvm_build
          sudo cmake --build .
      - name: Install LLVM
        run: |
          cd /llvm-build
          sudo mkdir /llvm-bin
          sudo cmake -DCMAKE_INSTALL_PREFIX=/llvm-bin -P cmake_install.cmake
          sudo cmake --build . --target install
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: /llvm-bin/bin/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: /llvm-bin/lib/
      - name: Upload include artifacts
        uses: actions/upload-artifact@v2
        with:
          name: include
          path: /llvm-bin/include/
