name: Compile LLVM

on: [push]

jobs:
  compile-llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Download LLVM sources
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          ref: release/11.x
      - name: Configure CMake
        run: |
          mkdir $GITHUB_WORKSPACE/llvm-build
          cd $GITHUB_WORKSPACE/llvm-build
          cmake $GITHUB_WORKSPACE/llvm
      - name: Compile LLVM
        run: |
          cd $GITHUB_WORKSPACE/llvm_build
          cmake --build .
      - name: Install LLVM
        run: |
          cd $GITHUB_WORKSPACE/llvm-build
          mkdir $GITHUB_WORKSPACE/llvm-bin
          cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/llvm-bin -P cmake_install.cmake
          cmake --build . --target install
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: $GITHUB_WORKSPACE/llvm-bin/bin/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: $GITHUB_WORKSPACE/llvm-bin/lib/
      - name: Upload include artifacts
        uses: actions/upload-artifact@v2
        with:
          name: include
          path: $GITHUB_WORKSPACE/llvm-bin/include/
