name: Compile LLVM

on: [push]

jobs:
  compile-llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Install llvmenv
        run: cargo install llvmenv
      - name: Compile LLVM
        run: llvmenv build-entry 11.0.0
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: llvm-11.0.0
          path: ~/.local/share/llvmenv
